import type { RoadmapAssessment } from '@/types/roadmap.type';

export const MOCK_ASSESSMENT: RoadmapAssessment = {
  service_name: "Passfolio",
  dev_type: "풀스택 웹 서비스",
  primary_roles: ["Frontend Developer", "Backend Developer"],
  secondary_roles: ["DevOps Engineer"],
  per_role: {
    "Frontend Developer": {
      coverage_level: "Senior",
      coverage_pct: 72.5,
      topic_coverage: "29/40",
      sequence: {
        frontier_topic: "WebSocket / 실시간 통신",
        contiguous_until: "성능 최적화",
        in_order_ratio: 0.84,
        skipped_core_prereqs: ["Testing (Jest, Vitest)"],
        skipped_support_prereqs: ["Storybook", "i18n"],
        verdict: "핵심 토픽은 순서대로 잘 학습되었으나 테스트 영역이 상대적으로 부족합니다. WebSocket 학습 전 상태관리 심화가 권장됩니다.",
      },
      roadmap_path: [
        { step: 1, topic: "HTML/CSS 기초", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 2, topic: "JavaScript ES6+", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 3, topic: "TypeScript", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 4, topic: "React", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: true },
        { step: 5, topic: "상태관리 (Zustand/Redux)", tier: "core", status: "partial", subtopics_to_learn: ["Redux Toolkit", "미들웨어"], market_tier: "주류", highlighted: true },
        { step: 6, topic: "React Query", tier: "support", status: "covered", subtopics_to_learn: [], market_tier: "급부상", highlighted: false },
        { step: 7, topic: "Tailwind CSS", tier: "support", status: "covered", subtopics_to_learn: [], market_tier: "주류", highlighted: false },
        { step: 8, topic: "성능 최적화", tier: "core", status: "partial", subtopics_to_learn: ["Code Splitting", "Lazy Loading", "Web Vitals"], market_tier: "필수", highlighted: true },
        { step: 9, topic: "Testing (Jest, Vitest)", tier: "core", status: "uncovered", subtopics_to_learn: ["단위 테스트", "통합 테스트", "RTL"], market_tier: "필수", highlighted: true },
        { step: 10, topic: "WebSocket / 실시간 통신", tier: "support", status: "uncovered", subtopics_to_learn: ["Socket.io", "SSE"], market_tier: "성장", highlighted: false },
        { step: 11, topic: "Next.js / SSR", tier: "core", status: "uncovered", subtopics_to_learn: ["App Router", "ISR", "Server Components"], market_tier: "필수", highlighted: true },
        { step: 12, topic: "CI/CD (GitHub Actions)", tier: "support", status: "covered", subtopics_to_learn: [], market_tier: "주류", highlighted: false },
      ],
      nodes: [
        // CORE — covered
        { label: "HTML/CSS 기초",          type: "topic",    parent: "", order: 5,  tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "JavaScript ES6+",        type: "topic",    parent: "", order: 10, tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "TypeScript",             type: "topic",    parent: "", order: 18, tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "React",                  type: "topic",    parent: "", order: 25, tier: "core",    status: "covered",   market_tier: "필수", highlighted: true  },
        { label: "상태관리",               type: "topic",    parent: "", order: 32, tier: "core",    status: "partial",   market_tier: "주류", highlighted: true  },
        { label: "성능 최적화",            type: "topic",    parent: "", order: 44, tier: "core",    status: "partial",   market_tier: "필수", highlighted: true  },
        // CORE — uncovered
        { label: "Testing (Jest, Vitest)", type: "topic",    parent: "", order: 52, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: true  },
        { label: "Next.js / SSR",          type: "topic",    parent: "", order: 62, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: true  },
        // SUPPORT — covered
        { label: "React Query",            type: "topic",    parent: "", order: 34, tier: "support", status: "covered",   market_tier: "급부상", highlighted: false },
        { label: "Tailwind CSS",           type: "topic",    parent: "", order: 36, tier: "support", status: "covered",   market_tier: "주류",  highlighted: false },
        { label: "CI/CD (GitHub Actions)", type: "topic",    parent: "", order: 42, tier: "support", status: "covered",   market_tier: "주류",  highlighted: false },
        // SUPPORT — uncovered
        { label: "WebSocket / 실시간 통신",type: "topic",    parent: "", order: 56, tier: "support", status: "uncovered", market_tier: "성장",  highlighted: false },
        { label: "Storybook",              type: "topic",    parent: "", order: 60, tier: "support", status: "uncovered", market_tier: "중간",  highlighted: false },
        // subtopics
        { label: "Redux Toolkit",          type: "subtopic", parent: "상태관리",               order: 33, tier: "core",    status: "partial",   market_tier: "주류", highlighted: false },
        { label: "미들웨어",               type: "subtopic", parent: "상태관리",               order: 33, tier: "core",    status: "uncovered", market_tier: "중간", highlighted: false },
        { label: "Code Splitting",         type: "subtopic", parent: "성능 최적화",            order: 45, tier: "core",    status: "partial",   market_tier: "필수", highlighted: false },
        { label: "Lazy Loading",           type: "subtopic", parent: "성능 최적화",            order: 45, tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "Web Vitals",             type: "subtopic", parent: "성능 최적화",            order: 45, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: false },
        { label: "단위 테스트",            type: "subtopic", parent: "Testing (Jest, Vitest)", order: 53, tier: "core",    status: "uncovered", market_tier: "주류", highlighted: false },
        { label: "통합 테스트",            type: "subtopic", parent: "Testing (Jest, Vitest)", order: 53, tier: "core",    status: "uncovered", market_tier: "중간", highlighted: false },
        { label: "RTL",                    type: "subtopic", parent: "Testing (Jest, Vitest)", order: 53, tier: "core",    status: "uncovered", market_tier: "주류", highlighted: false },
        { label: "App Router",             type: "subtopic", parent: "Next.js / SSR",          order: 63, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: false },
        { label: "ISR",                    type: "subtopic", parent: "Next.js / SSR",          order: 63, tier: "core",    status: "uncovered", market_tier: "중간", highlighted: false },
        { label: "Server Components",      type: "subtopic", parent: "Next.js / SSR",          order: 63, tier: "core",    status: "uncovered", market_tier: "급부상", highlighted: false },
        { label: "Socket.io",              type: "subtopic", parent: "WebSocket / 실시간 통신", order: 57, tier: "support", status: "uncovered", market_tier: "성장", highlighted: false },
        { label: "SSE",                    type: "subtopic", parent: "WebSocket / 실시간 통신", order: 57, tier: "support", status: "uncovered", market_tier: "중간", highlighted: false },
      ],
      covered_count: 7,
      partial_count: 2,
      uncovered_count: 3,
    },
    "Backend Developer": {
      coverage_level: "Mid-Senior",
      coverage_pct: 58.3,
      topic_coverage: "21/36",
      sequence: {
        frontier_topic: "메시지 큐 (Kafka/RabbitMQ)",
        contiguous_until: "데이터베이스 최적화",
        in_order_ratio: 0.76,
        skipped_core_prereqs: ["보안 (OAuth2, JWT 심화)", "메시지 큐"],
        skipped_support_prereqs: ["모니터링 (Prometheus/Grafana)"],
        verdict: "API 설계와 데이터베이스까지는 탄탄하지만 분산 시스템과 보안 심화 영역 학습이 필요합니다.",
      },
      roadmap_path: [
        { step: 1, topic: "Python / Node.js 기초", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 2, topic: "REST API 설계", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 3, topic: "Django / FastAPI", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "주류", highlighted: false },
        { step: 4, topic: "SQL (PostgreSQL)", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 5, topic: "데이터베이스 최적화", tier: "core", status: "partial", subtopics_to_learn: ["인덱스 전략", "쿼리 최적화", "파티셔닝"], market_tier: "필수", highlighted: true },
        { step: 6, topic: "Redis / 캐싱", tier: "support", status: "covered", subtopics_to_learn: [], market_tier: "주류", highlighted: false },
        { step: 7, topic: "보안 (OAuth2, JWT 심화)", tier: "core", status: "uncovered", subtopics_to_learn: ["OIDC", "PKCE", "리프레시 토큰 전략"], market_tier: "필수", highlighted: true },
        { step: 8, topic: "메시지 큐 (Kafka/RabbitMQ)", tier: "core", status: "uncovered", subtopics_to_learn: ["Kafka 기초", "이벤트 소싱", "CQRS"], market_tier: "급부상", highlighted: true },
        { step: 9, topic: "컨테이너 (Docker/K8s)", tier: "support", status: "partial", subtopics_to_learn: ["K8s 배포", "Helm"], market_tier: "주류", highlighted: false },
      ],
      nodes: [
        // CORE — covered
        { label: "Python / Node.js 기초",       type: "topic",    parent: "", order: 5,  tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "REST API 설계",               type: "topic",    parent: "", order: 10, tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "Django / FastAPI",            type: "topic",    parent: "", order: 15, tier: "core",    status: "covered",   market_tier: "주류", highlighted: false },
        { label: "SQL (PostgreSQL)",            type: "topic",    parent: "", order: 20, tier: "core",    status: "covered",   market_tier: "필수", highlighted: false },
        { label: "데이터베이스 최적화",          type: "topic",    parent: "", order: 28, tier: "core",    status: "partial",   market_tier: "필수", highlighted: true  },
        // CORE — uncovered
        { label: "보안 (OAuth2, JWT 심화)",     type: "topic",    parent: "", order: 40, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: true  },
        { label: "메시지 큐 (Kafka/RabbitMQ)", type: "topic",    parent: "", order: 48, tier: "core",    status: "uncovered", market_tier: "급부상", highlighted: true  },
        // SUPPORT — covered
        { label: "Redis / 캐싱",               type: "topic",    parent: "", order: 25, tier: "support", status: "covered",   market_tier: "주류", highlighted: false },
        // SUPPORT — partial
        { label: "컨테이너 (Docker/K8s)",      type: "topic",    parent: "", order: 35, tier: "support", status: "partial",   market_tier: "주류", highlighted: false },
        // subtopics
        { label: "인덱스 전략",                type: "subtopic", parent: "데이터베이스 최적화",       order: 29, tier: "core",    status: "partial",   market_tier: "필수", highlighted: false },
        { label: "쿼리 최적화",               type: "subtopic", parent: "데이터베이스 최적화",        order: 29, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: false },
        { label: "파티셔닝",                  type: "subtopic", parent: "데이터베이스 최적화",        order: 29, tier: "core",    status: "uncovered", market_tier: "중간", highlighted: false },
        { label: "OIDC",                      type: "subtopic", parent: "보안 (OAuth2, JWT 심화)",   order: 41, tier: "core",    status: "uncovered", market_tier: "필수", highlighted: false },
        { label: "PKCE",                      type: "subtopic", parent: "보안 (OAuth2, JWT 심화)",   order: 41, tier: "core",    status: "uncovered", market_tier: "주류", highlighted: false },
        { label: "리프레시 토큰 전략",         type: "subtopic", parent: "보안 (OAuth2, JWT 심화)",   order: 41, tier: "core",    status: "uncovered", market_tier: "주류", highlighted: false },
        { label: "Kafka 기초",                type: "subtopic", parent: "메시지 큐 (Kafka/RabbitMQ)", order: 49, tier: "core",    status: "uncovered", market_tier: "급부상", highlighted: false },
        { label: "이벤트 소싱",               type: "subtopic", parent: "메시지 큐 (Kafka/RabbitMQ)", order: 49, tier: "core",    status: "uncovered", market_tier: "성장", highlighted: false },
        { label: "CQRS",                      type: "subtopic", parent: "메시지 큐 (Kafka/RabbitMQ)", order: 49, tier: "core",    status: "uncovered", market_tier: "성장", highlighted: false },
        { label: "K8s 배포",                  type: "subtopic", parent: "컨테이너 (Docker/K8s)",     order: 36, tier: "support", status: "uncovered", market_tier: "주류", highlighted: false },
        { label: "Helm",                      type: "subtopic", parent: "컨테이너 (Docker/K8s)",     order: 36, tier: "support", status: "uncovered", market_tier: "중간", highlighted: false },
      ],
      covered_count: 5,
      partial_count: 2,
      uncovered_count: 2,
    },
    "DevOps Engineer": {
      coverage_level: "Junior-Mid",
      coverage_pct: 38.0,
      topic_coverage: "9/24",
      sequence: {
        frontier_topic: "Kubernetes",
        contiguous_until: "Docker",
        in_order_ratio: 0.65,
        skipped_core_prereqs: ["Kubernetes", "Terraform", "모니터링"],
        skipped_support_prereqs: ["ArgoCD", "Vault"],
        verdict: "Docker와 기본 CI/CD는 갖춰져 있으나 오케스트레이션과 IaC 영역 학습이 우선됩니다.",
      },
      roadmap_path: [
        { step: 1, topic: "Linux / Shell", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 2, topic: "Docker", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "필수", highlighted: false },
        { step: 3, topic: "GitHub Actions / CI", tier: "core", status: "covered", subtopics_to_learn: [], market_tier: "주류", highlighted: false },
        { step: 4, topic: "Kubernetes", tier: "core", status: "uncovered", subtopics_to_learn: ["Pod/Service/Ingress", "HPA", "Helm"], market_tier: "필수", highlighted: true },
        { step: 5, topic: "Terraform / IaC", tier: "core", status: "uncovered", subtopics_to_learn: ["모듈 설계", "State 관리"], market_tier: "주류", highlighted: true },
        { step: 6, topic: "모니터링 (Prometheus/Grafana)", tier: "support", status: "uncovered", subtopics_to_learn: ["메트릭 수집", "알람 설정"], market_tier: "성장", highlighted: false },
      ],
      nodes: [],
      covered_count: 3,
      partial_count: 0,
      uncovered_count: 3,
    },
  },
  llm_assessment: {
    overall_level: "Senior",
    level_rationale: "React와 TypeScript 기반의 프론트엔드 구현 역량이 매우 탄탄하며, 백엔드 API 설계와 데이터베이스 활용도 준수한 수준입니다. 다만 테스트 자동화, 분산 시스템, 보안 심화 영역에서 성장 여지가 있어 Senior 초입으로 평가됩니다.",
    strong_areas: [
      { area: "React / TypeScript 생산성", reason: "컴포넌트 설계, 훅 패턴, 타입 안전성이 전반적으로 높은 수준이며 실제 서비스에 적용된 사례가 다수 존재합니다." },
      { area: "API 설계 및 통신 레이어", reason: "Axios 인터셉터, 토큰 갱신 전략, 에러 처리 등 프로덕션 수준의 HTTP 레이어가 갖춰져 있습니다." },
    ],
    gap_areas: [
      { area: "테스트 자동화", priority: "High", reason: "단위/통합 테스트 커버리지가 낮아 리팩토링 안전망이 부족합니다. Jest + RTL 또는 Vitest 도입이 시급합니다." },
      { area: "분산 시스템 (Kafka, Redis Pub/Sub)", priority: "High", reason: "실시간 기능 확장과 서비스 간 결합도 감소를 위해 메시지 큐 개념이 필요합니다." },
      { area: "Next.js / SSR", priority: "Medium", reason: "SEO와 초기 로딩 성능을 위해 SSR/SSG 전략이 현 서비스에 적합합니다." },
    ],
    roadmap_path: [
      { step: 1, topic: "HTML/CSS 기초", tier: "core", subtopics_to_learn: [], why: "모든 웹 개발의 기반", how: "MDN 공식 문서와 실습 프로젝트로 학습" },
      { step: 2, topic: "JavaScript ES6+", tier: "core", subtopics_to_learn: [], why: "브라우저 동작 원리 이해에 필수", how: "You Don't Know JS 시리즈 + 코딩 챌린지" },
      { step: 3, topic: "TypeScript", tier: "core", subtopics_to_learn: [], why: "타입 안전성으로 버그 사전 방지", how: "공식 핸드북 + 실무 프로젝트 적용" },
      { step: 4, topic: "React", tier: "core", subtopics_to_learn: [], why: "국내외 채용 시장 1위 프론트엔드 프레임워크", how: "공식 docs beta + 사이드 프로젝트" },
      { step: 5, topic: "상태관리 (Zustand/Redux)", tier: "core", subtopics_to_learn: ["Redux Toolkit", "미들웨어"], why: "복잡한 앱 상태를 예측 가능하게 관리", how: "Zustand로 시작 후 Redux Toolkit으로 확장" },
      { step: 6, topic: "Testing (Jest, Vitest)", tier: "core", subtopics_to_learn: ["단위 테스트", "통합 테스트", "RTL"], why: "리팩토링 안전망과 코드 품질 보증", how: "기존 컴포넌트에 RTL 테스트부터 추가 시작" },
      { step: 7, topic: "성능 최적화", tier: "core", subtopics_to_learn: ["Code Splitting", "Lazy Loading", "Web Vitals"], why: "사용자 경험과 SEO에 직결", how: "Lighthouse로 현재 지표 측정 후 개선 작업" },
      { step: 8, topic: "Next.js / SSR", tier: "core", subtopics_to_learn: ["App Router", "ISR", "Server Components"], why: "SSR/SSG로 SEO와 초기 로딩 최적화", how: "공식 튜토리얼 + 현 서비스 마이그레이션 실험" },
      { step: 9, topic: "메시지 큐 (Kafka/RabbitMQ)", tier: "support", subtopics_to_learn: ["Kafka 기초", "이벤트 소싱"], why: "서비스 간 비동기 통신과 확장성 확보", how: "Docker로 Kafka 로컬 실습 환경 구성" },
    ],
    summary: "탄탄한 React/TypeScript 역량을 기반으로 풀스택 서비스를 구축한 경험이 강점입니다. 테스트 자동화 도입과 Next.js SSR 전환을 통해 시니어 레벨을 더욱 공고히 할 수 있으며, 분산 시스템 학습을 병행하면 백엔드 아키텍처 설계 역량도 크게 향상될 것입니다.",
  },
  market_brief: {
    market_overview: "2024~2025년 국내 프론트엔드 채용 시장은 React 기반 풀스택 역량을 보유한 시니어 개발자 수요가 지속적으로 높습니다. TypeScript 필수화, 테스트 자동화 요구가 증가하고 있으며 Next.js SSR 경험이 차별화 포인트로 부상했습니다.",
    trending_stacks: [
      { stack: "Next.js 14 (App Router)", trend: "급상승", kr_demand_pct: 64, reason: "SSR/RSC로 SEO와 성능을 동시에 잡는 표준이 되고 있습니다." },
      { stack: "Zustand + React Query", trend: "상승", kr_demand_pct: 51, reason: "보일러플레이트 없이 서버·클라이언트 상태를 분리하는 조합으로 빠르게 표준화 중입니다." },
      { stack: "Vitest + Testing Library", trend: "상승", kr_demand_pct: 43, reason: "Vite 생태계 확산과 함께 테스트 도입 진입장벽이 낮아지고 있습니다." },
    ],
    declining_stacks: [
      { stack: "Class Components (React)", reason: "함수형 + 훅 패턴으로 완전히 대체되어 신규 채용 JD에서 거의 사라졌습니다." },
      { stack: "Redux (vanilla)", reason: "Redux Toolkit으로 이전 가속화, Zustand에게도 빠르게 점유율 빼앗기는 중입니다." },
    ],
    company_patterns: {
      startup: "빠른 출시 위해 Next.js + Supabase 조합이 대세. 풀스택 1인 개발 역량 중시.",
      enterprise: "마이크로 프론트엔드, 디자인 시스템, 테스트 커버리지 정책이 핵심 채용 기준.",
    },
    salary_context: "국내 시니어 프론트엔드(5년+) 연봉 밴드는 6,000~9,000만원 수준이며, Next.js + 테스트 자동화 경험 보유 시 상단 밴드 협상이 가능합니다.",
    user_market_position: "React/TypeScript 실무 경험이 시장 평균을 상회하며, 풀스택 서비스 구축 이력이 스타트업 포지션에서 경쟁력 있습니다. 테스트와 SSR 경험을 보강하면 대기업 포지션도 충분히 도달 가능합니다.",
    strategic_direction: "Next.js 마이그레이션 + 테스트 커버리지 50% 달성을 6개월 목표로 설정하고, 이를 포트폴리오에 정량 지표로 제시하는 전략을 권장합니다.",
    priority_skills: [
      { skill: "Testing (Jest/Vitest + RTL)", urgency: "urgent", market_demand: "매우 높음", reason: "Senior 포지션 JD의 78%에서 테스트 역량을 명시적으로 요구합니다." },
      { skill: "Next.js (App Router)", urgency: "urgent", market_demand: "매우 높음", reason: "2025년 기준 React 기반 채용의 64%가 Next.js 경험을 우선 요건으로 제시합니다." },
      { skill: "성능 최적화 (Web Vitals)", urgency: "important", market_demand: "높음", reason: "LCP/CLS/INP 지표 개선 경험이 기술 면접의 단골 주제입니다." },
      { skill: "메시지 큐 (Kafka 기초)", urgency: "nice-to-have", market_demand: "중간", reason: "풀스택 확장을 원한다면 비동기 아키텍처 이해가 장기적으로 필요합니다." },
    ],
  },
};
